### PR TITLE
Possibility to start Qaop with mvn exec:java

### PR DESCRIPTION
**Pull request by mnummeli**
I have added exec-maven-plugin to allow running project with mvn exec:java from command line.

### CODE REVIEW

**Comment by anjackson** [comment]
Did you mean to close this?

**Comment by mnummeli** [comment]
Sorry, closed it accidentally prematurely.

**Comment by anjackson** [comment]
Sorry for accidentally ignoring this (we don't use qaop at the moment). The original change looks fine. The file formatting isn't really necessary, but happy to merge if that's what you intended?

**Comment by mnummeli** [comment]
That is OK.

- Mikko N.

pe 31. tammik. 2020 klo 14.21 Andy Jackson (notifications@github.com)
kirjoitti:

**Pull request merged**
